replicaCount: 1
image:
  repository: netflix
  tag: latest
  pullPolicy: IfNotPresent
canary:
  enabled: false
  tag: canary
  replicaCount: 1
  weight: 20 # Percentage of traffic to canary
service:
  type: NodePort
  port: 80
ingress:
  enabled: true
  className: traefik
  hosts:
  - host: netflix.local
    paths:
    - path: /
      pathType: Prefix
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
