{{- if .Values.canary.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: netflix-clone-canary
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
    traefik.ingress.kubernetes.io/router.priority: "10"
    traefik.ingress.kubernetes.io/router.middlewares: netflix-clone-main@kubernetescrd, netflix-clone-canary@kubernetescrd
spec:
  rules:
    - host: netflix.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: netflix-clone-canary
                port:
                  number: {{ $.Values.service.port }}
{{- end }}
